= Introduction and goals
:navtitle: Introduction

== Project overview

Beep is a social media platform and instant messaging web application with real-time video and audio capabilites, file sharing, and more.

== Document overview

The target of this document is to archive the collection of architecture decision records for the Beep project technical architecture. Each architecture decision record (ADR) addresses a specific technical architecture decision and decides on a solution to a problem, documenting the context and reasons for that decision. 

You can find the Technical Architecture Document (TAD) by clicking the lower left corner of the page and switching to the "Technical Architecture Document" site.

When coming across diagrams, you can click on them to open them in full for a better look.

== Intended audience

This document is intended for the team of contributors to the Beep project, and others involved in the design and implementation of the system, as well as any stakeholder or individual interested in the technical architecture of the project.

== Requirements language

The language defined below may be used in the following ADRs to minimize ambiguity and ensure clarity in the requirements and decisions made.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in link:https://www.rfc-editor.org/info/bcp14[BCP 14] (link:https://datatracker.ietf.org/doc/html/rfc2119[RFC 2119], link:https://datatracker.ietf.org/doc/html/rfc8174[RFC 8174]) when, and only when, they appear in all capitals, as shown here.

== Stakeholders

[cols="2,2,3"]
|===
|Name |Role |Contact

|HÉRITIER Léo
|Project overseer & Client
|leo.heritier at umontpellier.fr

|SOULTANEM Frédéric
|Documentation overseer & Client
|frederic.soultanem at gmail.com

|TCHILINGUIRIAN Théo
|Project contributor
|theo.tchilinguirian at etu.umontpellier.fr

|DO Students
|Project contributors
|theo.tchilinguirian at etu.umontpellier.fr

|===
