= I. Separating Beep into functional neighborhoods and microservices

== 3. Separating Beep's user stories into functional neighborhoods, contexts and services

In this section, we will classify the user stories we identified into functional neighborhoods, and I will give my proposal for breaking down Beep into microservices.

=== Identifying functional neighborhoods and bounded contexts

A functional neighborhood is a group of functionalities that are related to a specific business capability of Beep.
// Is it a bit late to define this term? Or is it good here? Follow where each term is defined. Also add them to the glossary? If we assume the reader doesn't know these terms? See how it's done in academics. Who would read this?
// This definition is worth nothing if "business capability" isn't defined earlier.

Some common pitfalls to avoid when defining functional neighborhoods and cutting microservices are:

- Defining functional neighborhoods based on the current architecture, rather than the business capabilities of Beep,
- Defining functional neighborhoods that are too tightly coupled,
- Identifying microservices from the database schema, which is an anti-pattern so common it has a name: "Entity-Service Anti-Pattern". This results in distributed monoliths where each service becomes a CRUD wrapper around a table, leading to excessive coupling and communication between services, causing performance issues.

Generally, this comes down to not following the microservices architecture as we defined it earlier.

In order to avoid those pitfalls and more correctly identify which microservices should make up Beep's architecture in a way that fulfills all of the user stories and business capabilities of Beep, we have to examine the current architecture, database schema, levels of dependency between components of the current monolith, and more. This will allow us to consider, and better avoid past architectural truths while designing the new architecture, which is to be based on services revolving around business capabilities. In order to do that, we will apply some principles of Domain-Driven Development, such as identifying bounded contexts.

// Idea: presenting a view of the current database schema before this section could help identify tight couplings, and thus help group stuff(?) into services? Maybe? Explore this possibility.

//TODO: review DDD to see where this part (right below) needs rethinking. Also define DDD somewhere. Glossary+linkreference to it.

We may start by identifying the main domains Beep revolves around.

- Authentication of users and user management
- Real-time communication and instant messaging and file sharing
- Management and retrieval of large quantities of files and other stored media

This first repartition of domains us a basic idea of what domains Beep's business capabilities, and the user stories they resolve, mainly revolve around. However, we need to break down and regroup these domains further, avoiding tight levels of coupling between them and their components. +
Some parts of Beep are clearly more independent than others. These can already be set astide into their own "contexts", such as the authentication system, the real-time communication system, instant messaging system, media storage system, search system (which would search accross for resources across other systems), and the notification system (which would notify users' devices on events happening from other systems). +

These couplings are starting to make more sense. There are features in Beep that we didn't mention yet, such as server lifecycle management: settings, invitations; as well as roles and permissions. +
The lifecycle of servers in Beep is currently pretty simple, but that means it's bound to have many features added soon. That means it's important to future-proof this system as of now, by thinking about the possible user stories and business capabilities that could revolve around it in the future. +
Currently, server lifecycle includes servers settings (names, etc.) as well as invitation links. But in the future, this could include communities, groupings of servers, academic communities available for students via their academic emails - for example. +
Entirely future-proofing a system is not an easy task, and would require a document of its own. However, some basic principles can be applied to make most of the future-proofing have effect. Building a smart and common abstraction over the current models, and avoiding repetition are such core principles. +

As such, all of this could be considered to constitute its own "server lifecycle management" context.

And while we're structuring our services, let's keep in mind the common pitfalls we may involuntarily fall into. Especially the "Entity-Service Anti-Pattern", defined above.

We have identifies contexts around which to define Beep's future microservices architecture. To further refine these contexts, we can draw a "context map" to clearly identify the contexts around which services should be grouped.

//Review DDD's bounded contexts around here.

//We will apply principles of DDD (such as bounded contexts) and ... to... avoid...
//TODO: draw a "context map"!! To clearly identify the contexts around which services should be grouped.
https://medium.com/@mike_7149/context-mapping-4b4909cf195a
Context map draft

- Authentication context (authenticating any request, external (users, bots/webhooks) or maybe even internal (authenticate services) (that's hypothetical for now)
- Authorization context (Manage RBAC, ABAC and PBAC. Apply policies between/across services to users queries/requests, etc.)
- Chatting context (messages, files, "text" channels lifecycle management)
- Video/audio calls context (handles all the media, real-time audio/video/screen sharing logic/features, and "voice" channels lifecycle management)
- Notifications context (push notifications to devices. At least that would need a message queuing...)
- User context (users and their settings)
- Search context (search for servers (overview page), channels, users, messages, files... Anything)
- Communities/servers context (manage communities/servers lifecycle, crud, invitations/... Potential future features such as groupings of servers as communities/...)

-> Check how do these contexts organize around teams, features, and how they'd interact with each other ; to make sure it's correct.

// /!\ https://medium.com/@vladikk.com/bounded-contexts-are-not-microservices-ead44b8d6e35 Bounded context != microservice.. Be CAUTIOUS! Review DD and rethink what you're doing? Define a basic ubiquitous language for Beep? In the component diagram(), for the interfaces?) maybe?

In earlier sections, we identified the user stories and functionalities beep must provide. We then classified them into bounded contexts following domain-driven development principles. From these previous analyses, I will propose a separation of Beep into microservices.

Should authorization be implemented as a separate service? Or sidecar proxy component? Central or distributed policy store? Or etc. Will be seen in chapter IV.

If we take future features into account, we would add a "search" service, taking care of the search for users, messages, files and other elements across storage systems.

We can be tempted to separate Beep into microservices following the current SQL database's schema and relations, that we saw in the initial chapter. But this would be a mistake, since as we defined in the initial chapter, microservices should be organized around business capabilities; and the current database schema is not a faithful representation of Beep's business capabilities, as opposed to the user stories, business capabilities and functionalities their represent, that we identified in the earlier sections. +
If we had defined Beep's microservices architecture from its initial database schema, we would end up with a distributed monolithic architecture, with tightly coupled services, a lot of inter-service communication, and thus scalability, and other benefits of a microservices architecture would be impacted.

Also doesn't make sense since databases will be separated into their own services and can be designed completely independently of the rest of the system. They become not part of the business capabilities of Beep, but really just tools to store and retrieve data/state for each service.

Also also, how can we have a notification service... Without a message queuing system?? We'd have to use some other way like... Mongodb... To manage the push notifs state... Ugh. It's just a hacky hack, compared to a message queue. Or we'd assume that every device in the world who runs Beep is always on and has a stable connection to Beep (so that there would be no state to manage).
OH I KNOW!! We get rid of mobile push notifications (so no need for kafka, or third parties), and for the browser, we use a websocket. I suppose it would work for browser notifications into desktop notifications.. Maybe??

=== Component diagram for Beep's separation into microservices

These functional neighborhoods/business capabilities/... can be formally represented using a UML component diagram. Below is the resulting UML component diagram describing my proposal for Beep's separation into microservices.

.Component diagram for Beep's separation into microservices. Made with draw.io
image::images/fig3.component/beep-uml-component-diagram-light.svg[Component diagram showing Beep's architecture separat
ed into microservices.]

//TODO: refaire un second diagramme de composants avec des blocs au lieu des services et dedans deux composants : l'applicatif et la bdd associée.

====
**WIP**

> "Deciding what capability to decouple when and how to migrate incrementally are some of the architectural challenges of decomposing a monolith to an ecosystem of microservices."

Methods to break down the monolith:

Decompose services by business capabilities : reflect organization behavior. -> component diagram. +
En partant du domaine (communications temps réel), on va créer les différents services. Attention aux services qui communiquent beaucoup entre eux : **combiner les services**. +
https://12factor.net/ +
"The philosophy of Twelve-Factor turned out to be surprisingly timeless. More than a decade later, people still find its insights valuable, and it's often cited as a solid set of best practices for application development. But while the concepts remain relevant, many of the details have started to show their age." +
Domain-Driven Development. Application est construite sous forme d'abstractions au dessus de notre modèle.

Obstacles à la décomposition : network latency, data inconsistency/interfaces, god classes (fait tout, dure à décomposer, big) and reduced availability. Énormément de contextes sont impactés.

Architecture bien définie avec le DDD, bounded contexts. Architecture (enables org & proc), organization (enables proc) et process de développement => rapid, frequent & reliable delivery of software. +
**1 service = 1 responsabilité. Un service rendu. N'est responsable que d'une chose à faire.** +
Guidelines : +
Dur à faire mais génial : signifie une bonne séparation des services : c'est le **Common Closure Pattern**. +
En gros, une règle business n'affecte que 1 microservice, pas deux ou plus (si cette règle évolue il faudrait modifier plusieurs services...) +
Disons que j'ai à modifier le mode de livraison : que ça ne soit fait que dans un seul service !!! +
**Open Closed Princple** : on veut pouvoir intégrer facilement d'autres contrats d'API sans avoir à changer le coeur de fonctionnalités !!! -> Réelle abstraction. Logique non liée aux contrats d'APIs. => Des interfaces/contrats d'API génériques (comme un filesystem : create, read, update, delete, open d'un objet générique (fichier) ET NON PAS un type de fichier spécifique. C'est toujours que des fichiers ultra génériques avec leurs mêmes attributs communs : nom, taille, permissions, etc.) +
Quality of a service: scalable, reliable, secure, maintainable, testable, etc. +
=> Implementable functionalities are dependent on the quality of the architecture design. Future-proof design, stays easy to update with features, good abstractions (see how good filesystems are :3) +
Liskov principle, ouvert en extension fermé en modification (en gros les bonnes abstractions type filesystem) +
Je veux utiliser une autre bdd. Ou en utiliser plusieurs. Service and repository pattern. Hexagonal architecture. Des adaptateurs (que l'on branche sur un port) qui permettent de réaliser des opérations qui soient indépendantes de ce qu'il y a derrière (mongodb, postgres, filesystem...!! C'est dans l'adaptateur qu'on définit ça) +

https://www.uml-diagrams.org/component-diagrams.html
https://developer.ibm.com/articles/the-component-diagram/
====

Reading a component diagram: components are strictly logical, design-time constructs. The idea is that you can easily reuse and/or substitute a different component implementation in your designs because a component encapsulates behavior and implements specified interfaces.

This diagram is a first draft of the separation of Beep into microservices. This draft will be refined and completed further in the following sections, where we will take into account multiple other issues such as authentication, authorization, observability and many more.

(Authentication and) authorization (centralized, or decentralized store/policy agent? will depend on tech used. See corresponding chapter) services do not appear in this diagram will be defined in later chapters.

This component diagram only illustrates components and their interactions. It is not a proposal for inter-services communication, which will be studied in the next chapter.

Also there isn't the frontend, surrounding load balancer and API gateway, which allows the frontend to reach API endpoints that lead to different services, and authenticate the requests via JWT.

// TODO: maybe consider the database-per-service pattern here, and in the diagram (representing them).

=== 4. How Beep can be migrated to a microservices architecture: breaking down the monolith

Earlier, we saw an overview of Beep's current architecture, of the microservices architecture, and why Beep should consider migrating to a microservices architecture. +
In the last section, we went over my proposal to separate Beep into functional neighborhoods and microservices. +
In this section, we will briefly go over how the Beep team can break down the application into microservices.

In this section, we consider that the earlier chapters have been read and understood by the team, including the microservices architecture, as well as the separation of Beep into bounded contexts.

There are two main ways the Beep team could break down the monolith:

- The incremental way,
- Or a complete redesign and reimplementation.

A complete redesign and reimplementation may seem like a sound idea at first, but when studied with a critical eye on resources management and common operational principles, it becomes obvious that this choice is soldem the right one. +

Limits in resources such as time, effort or hands would need to be much more than sufficient to entirely replace the current architecture at once. Maintenance and the rate of delivery of new features and on the current system would suffer greatly.

On the contrary, incrementally redesigning and reimplementing groupings of features as new services, bounded inside their own contexts, and responsible of their own technology stack and business capabilities, would allow the Beep team to gradually replace parts of the current monolith with services, rendering the operational management of resources completely feasible across the team, with minimal impact on the current system's integrity, management, or feature delivery lifecycle.

Moreover, by concentrating the efforts of some on the implementation of a new service, this approach may also be just as fast, if not faster than the former approach.


**Sources for the chapter:**

https://microservices.io/refactoring/
https://microservices.io/patterns/
https://microservices.io/patterns/microservices.html
https://microservices.io/patterns/decomposition/decompose-by-business-capability.html
https://microservices.io/patterns/data/saga.html
https://microservices.io/post/refactoring/2019/10/09/refactoring-to-microservices.html
https://microservices.io/post/architecture/2024/08/27/architecting-microservices-for-fast-flow.html

Gérer les migrations de bdd, les insertions de bdd dans une architecture microservices ? -> Trino !! (? Piste à explorer).
https://trino.io/blog/2020/06/16/presto-summit-zuora.html PS: Trino s'appelait PrestoSQL avant.
https://moduscreate.com/blog/microservices-databases-migrations/
Paraît que marche encore mieux avec les trucs datalake, Hive, Iceberg...

use kafka for inter-microservices communication?
https://www.youtube.com/watch?v=Vz2DHAHn7OU

Was told this is a good tutorial to understand async await (in rust at least, but maybe in general!): https://tokio.rs/tokio/tutorial
https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/
https://stackoverflow.com/questions/60457740/rest-endpoint-for-complex-actions
https://stackoverflow.com/a/60463179

when is microservice not a good pattern
https://dzone.com/articles/10-microservices-anti-patterns-you-need-to-avoid

- https://microservices.io/articles/glossary#dora-metrics
- https://martinfowler.com/bliki/BoundedContext.html
- https://martinfowler.com/articles/break-monolith-into-microservices.html
- https://leofvo.me/articles/microservices-for-the-win
- https://www.geeksforgeeks.org/how-discord-scaled-to-15-million-users-on-one-server/
- https://samarthasthan.com/posts/building-a-scalable-e-commerce-empire-a-micro-services-system-design-approach/
- https://freedium.cfd/https://medium.com/@samarthasthan/from-zero-to-millions-crafting-a-scalable-discord-with-micro-services-0e55e65f2a16
- https://microservices.io/patterns/decomposition/decompose-by-business-capability.html
- https://microservices.io/patterns/microservices.html
- https://microservices.io/articles/glossary#dora-metrics
- https://microservices.io/patterns/data/database-per-service.html
- https://microservices.io/patterns/data/saga.html
- https://stackoverflow.com/questions/60071074/microservices-dependencies-in-uml-diagrams
- https://www.uml-diagrams.org/component-diagrams.html
- https://developer.ibm.com/articles/the-component-diagram/
- https://www.edrawsoft.com/fr/article/microservices-architecture-diagram.html

====
WIP

Listen to DIS https://www.youtube.com/watch?v=rv4LlmLmVWk

POUR LA BDD DE MESSAGES : MONGO!!! car relationnel déjà pour le search... Mais aussi pour quand ds le msg y'a une image/un msg vocal, ne pas avoir 90% de champs null dans la postgres pour tous les msgs qui en ont pas... Et si y'a, dans le mongo, mettre l'url du file service/object storage/CDN/FTP...

https://microservices.io/patterns/decomposition/decompose-by-business-capability.html
https://microservices.io/patterns/data/database-per-service.html
====

The purpose of this schema is to capture the requirements of Beep considering its users. This will help us outline business capabilities and user stories into functional neighborhoods, and thus redefine Beep into microservices.
//TODO: stop the blabla between business capabilities and user stories. Time to be clear and concise, bro. Yeah.

A business capability is the expression or articulation of the capacity, materials, and expertise an organization needs to perform core functions.
